base_seed: &MY_SEED 42

datasets:
  hidden-manifold:
    data_path: "datasets/hidden-manifold/"
    dim: 8
    diff: False

feature_extractor:
  random_circuit:
    measure: False
    seed: *MY_SEED
    num_qubits: 8
    depth: 5

training:
  solver: "adam"
  hidden_layer_sizes: []
  random_state: *MY_SEED
  max_iter: 300
  learning_rate: "constant"
  learning_rate_init: 0.01
  activation: "relu"
  early_stopping: True