seed: 42
experiment_name: "QMSC_Late_Fusion"
run_name: "Test"
model_name: "Test"

datasets:
  hidden-manifold:
    data_path: "datasets/hidden-manifold/"
    dim: 6
    diff: False

reservoir:
  num_qubits: 6

training:
  solver: "adam"
  hidden_layer_sizes: []
  max_iter: 300
  learning_rate: "constant"
  learning_rate_init: 0.01
  early_stopping: True
  n_folds: 5

evaluation:
  scoring: ["accuracy", "f1"]